USE ONLINESHOP
GO 
CREATE TABLE DOITAC(
MADT CHAR(15),
TENDT NVARCHAR(100),
DAIDIEN CHAR(15),
DIACHI NVARCHAR(100),
SLDH INT,
MALH CHAR(15),
DIACHIKD NVARCHAR(100),
SDT CHAR(15),
EMAIL VARCHAR(50),
PRIMARY KEY (MADT),
)
GO 
CREATE TABLE CHINHANH(
MACN CHAR(15),
MADT CHAR(15),
DIACHI NVARCHAR(100),
PRIMARY KEY(MACN)
)

GO
CREATE TABLE LOAIHANG(
MALOAI CHAR(15),
TENLOAI NVARCHAR(20),
PRIMARY KEY(MALOAI)
)

CREATE TABLE SANPHAM (
MASP CHAR(15),
TENSP NVARCHAR(100),
MALH CHAR(15),
PRIMARY KEY(MASP)
)

CREATE TABLE HOPDONG (
MAHD CHAR(15),
MADT CHAR(15),
SLCN INT,
TGBD DATETIME,
TGKT DATETIME,
HOAHONG INT,
PRIMARY KEY (MAHD)
)
CREATE TABLE DANGKI (
MACN CHAR(15),
MAHD CHAR(15),
PRIMARY KEY (MACN,MAHD)
)

CREATE TABLE QLSP(
MACN CHAR(15),
MASP CHAR(15),
PRIMARY KEY (MACN,MASP)
)

ALTER TABLE dbo.DOITAC ADD CONSTRAINT DOITAC_LOAIHANG FOREIGN KEY (MALH) REFERENCES dbo.LOAIHANG(MALOAI)
ALTER TABLE dbo.CHINHANH ADD CONSTRAINT CHINHANH_DOITAC FOREIGN KEY (MADT) REFERENCES dbo.DOITAC(MADT)
ALTER TABLE dbo.HOPDONG ADD CONSTRAINT HOPDONG_DOITAC FOREIGN KEY (MADT) REFERENCES dbo.DOITAC(MADT)
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT SANPHAM_LOAIHANG FOREIGN KEY(MALH) REFERENCES dbo.LOAIHANG(MALOAI)
ALTER TABLE dbo.DANGKI ADD CONSTRAINT DANGKI_CHINHANH FOREIGN KEY(MACN) REFERENCES dbo.CHINHANH(MACN), CONSTRAINT DANGKI_HOPDONG FOREIGN KEY (MAHD) REFERENCES dbo.HOPDONG(MAHD)
ALTER TABLE dbo.QLSP ADD CONSTRAINT QLSP_CHINHANH FOREIGN KEY(MACN) REFERENCES dbo.CHINHANH(MACN), CONSTRAINT QLSP_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)






