USE ONLINESHOP
GO 
-- Tạo bảng Đối tác
CREATE TABLE DOITAC (
	MADT CHAR(15),
	TENDT NVARCHAR(100),
	DAIDIEN CHAR(15),
	DIACHI NVARCHAR(100),
	SLDH INT,
	MALH CHAR(15),
	DIACHIKD NVARCHAR(100),
	SDT CHAR(15),
	EMAIL VARCHAR(50),
	PRIMARY KEY (MADT),
)
-- Tảo bảng Chi nhánh
CREATE TABLE CHINHANH (
	MACN CHAR(15),
	MADT CHAR(15),
	DIACHI NVARCHAR(100),
	PRIMARY KEY(MACN)
)
-- Tạo bảng Loại hàng
CREATE TABLE LOAIHANG (
	MALOAI CHAR(15),
	TENLOAI NVARCHAR(20),
	PRIMARY KEY(MALOAI)
)
-- Tạo bảng Sản phẩm
CREATE TABLE SANPHAM (
	MASP CHAR(15),
	TENSP NVARCHAR(100),
	MALH CHAR(15),
	PRIMARY KEY(MASP)
)
-- Tạo bảng Hợp đồng
CREATE TABLE HOPDONG (
	MAHD CHAR(15),
	MADT CHAR(15),
	SLCN INT,
	TGBD DATETIME,
	TGKT DATETIME,
	HOAHONG INT,
	PRIMARY KEY (MAHD)
)
-- Tạo bảng Đăng kí (Các chi nhánh đăng ký hợp đồng)
CREATE TABLE DANGKI (
	MACN CHAR(15),
	MAHD CHAR(15),
	PRIMARY KEY (MACN,MAHD)
)
-- Tạo bảng Quản lý sản phẩm (Sản phẩm thuộc chi nhánh nào)
CREATE TABLE QLSP(
	MACN CHAR(15),
	MASP CHAR(15),
	PRIMARY KEY (MACN,MASP)
)

-- Tạo bảng Khách hàng
CREATE TABLE KHACHHANG (
	MaKH CHAR(15) PRIMARY KEY,
	HoTen NVARCHAR(100),
	SDT CHAR(15),
	Diachi NVARCHAR(100),
	Email VARCHAR(50),
)
-- Tạo bảng Tài xế
CREATE TABLE TAIXE (
	MaTX CHAR(15) PRIMARY KEY,
	HoTen NVARCHAR(100),
	CMND CHAR(15),
	SDT CHAR(15),
	Diachi NVARCHAR(100),
	BienSo CHAR(10),
	KhuVuc NVARCHAR(100),
	Email VARCHAR(50),
	STK CHAR(20),
	NganHang NVARCHAR(50)
)
-- Tạo bảng Đơn hàng
CREATE TABLE DONHANG (
	MaDH CHAR(15) PRIMARY KEY,
	MaKH CHAR(15),
	MaTX CHAR(15),
	HinhThucTT VARCHAR(10),
	DiaChiGH NVARCHAR(100),
	PhiSP INT,
	PhiShip INT,
	TongTien INT,
	TrangThai INT
)
-- Tạo bảng Sản phẩm đơn hàng (Đơn hàng có sản phẩm nào, số lượng)
CREATE TABLE SPDH (
	MaDH CHAR(15),
	MaSP CHAR(15),
	SL INT
	PRIMARY KEY (MaDH, MaSP)
)

GO
ALTER TABLE dbo.DOITAC ADD CONSTRAINT DOITAC_LOAIHANG FOREIGN KEY (MALH) REFERENCES dbo.LOAIHANG(MALOAI)
ALTER TABLE dbo.CHINHANH ADD CONSTRAINT CHINHANH_DOITAC FOREIGN KEY (MADT) REFERENCES dbo.DOITAC(MADT)
ALTER TABLE dbo.HOPDONG ADD CONSTRAINT HOPDONG_DOITAC FOREIGN KEY (MADT) REFERENCES dbo.DOITAC(MADT)
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT SANPHAM_LOAIHANG FOREIGN KEY(MALH) REFERENCES dbo.LOAIHANG(MALOAI)
ALTER TABLE dbo.DANGKI ADD CONSTRAINT DANGKI_CHINHANH FOREIGN KEY(MACN) REFERENCES dbo.CHINHANH(MACN),
	CONSTRAINT DANGKI_HOPDONG FOREIGN KEY (MAHD) REFERENCES dbo.HOPDONG(MAHD)
ALTER TABLE dbo.QLSP ADD CONSTRAINT QLSP_CHINHANH FOREIGN KEY(MACN) REFERENCES dbo.CHINHANH(MACN),
	CONSTRAINT QLSP_SANPHAM FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)
ALTER TABLE dbo.DONHANG ADD FOREIGN KEY (MaKH) REFERENCES dbo.KHACHHANG(MaKH),
	FOREIGN KEY (MaTX) REFERENCES dbo.TAIXE(MaTX)
ALTER TABLE dbo.SPDH ADD FOREIGN KEY (MaDH) REFERENCES dbo.DONHANG(MaDH),
	FOREIGN KEY (MaSP) REFERENCES dbo.SANPHAM(MaSP)
